[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"
okhttp = "4.12.0"
moshi = "1.15.1"
toolbox-api = "1.3.47293"
plugin-structure = "3.320"
detekt = "1.23.8"
mockk = "1.14.7"
zt-exec = "1.12"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# JSON
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# HTTP
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Process execution
zt-exec = { module = "org.zeroturnaround:zt-exec", version.ref = "zt-exec" }

# Toolbox API
toolbox-core-api = { module = "com.jetbrains.toolbox:core-api", version.ref = "toolbox-api" }
toolbox-ui-api = { module = "com.jetbrains.toolbox:ui-api", version.ref = "toolbox-api" }
toolbox-remote-dev-api = { module = "com.jetbrains.toolbox:remote-dev-api", version.ref = "toolbox-api" }
plugin-structure-toolbox = { module = "org.jetbrains.intellij.plugins:structure-toolbox", version.ref = "plugin-structure" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
toolbox-plugin-api = ["toolbox-core-api", "toolbox-ui-api", "toolbox-remote-dev-api"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.20-1.0.32" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
